import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  CharacterSelectView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#22a1e6",
  },
  heading: {
    width: 300,
    color: "#eee",
    fontSize: 20,
    fontWeight: "500",
    textAlign: "center",
    alignItems: "center",
    letterSpacing: 1,
    marginBottom: 10,
    textShadowColor: "#444",
    textShadowRadius: 3,
    textShadowOffset: { width: -2.5, height: 2 },
  },
  boxesContainer: {
    width: 310,
    height: 600,
    borderWidth: 2,
    borderColor: "#444",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-evenly",
    paddingVertical: 4,
    paddingHorizontal: 0,
    backgroundColor: "#1f89c2",
  },
  characterBoxContainer: {
    shadowColor: "#444",
    shadowRadius: 5,
    shadowOpacity: 0.6,
    shadowOffset: { width: -2, height: 3 },
  },
  characterBox: {
    width: 139,
    height: 137,
    borderColor: "#fff",
    borderWidth: 0.5,
    marginTop: 5,
    marginBottom: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#22a1e6",
  },
  character: {
    width: 100,
    height: 100,
  },
  characterName: {
    color: "#222",
    fontSize: 13,
    fontWeight: "400",
  },
  lockedCharacter: {
    tintColor: "#222",
    opacity: 0.5,
  },
  lock: {
    position: "absolute",
    height: 62,
    width: 53,
  },
  closedLock: {
    position: "absolute",
    height: 48,
    width: 39,
  },
  keyInfoContainer: {
    position: "relative",
    width: 310,
    height: 100,
    borderWidth: 2,
    borderColor: "#444",
    marginTop: 10,
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#1f89c2",
  },
  keyBox: {
    width: 288,
    height: 80,
    borderWidth: 0.5,
    borderColor: "#fff",
    flexDirection: "row",
    justifyContent: "center",
    shadowColor: "#444",
    shadowOpacity: 0.6,
    shadowRadius: 5,
    shadowOffset: { width: -2, height: 3 },
    backgroundColor: "#22a1e6",
  },
  keyContainer: {
    flexDirection: "row",
  },
  keyContainerText: {
    color: "#222",
    paddingVertical: 23,
    marginLeft: 5,
    fontSize: 25,
  },
  key: {
    position: "relative",
    width: 65,
    height: 29,
    marginTop: 20,
    paddingVertical: 21,
  },
});

export default styles;
