import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  gameView: {
    flex: 1,
    backgroundColor: "black",
  },
  backgroundImage: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    opacity: 0.2,
    width: Values.maxW,
    height: Values.maxH,
  },
  bubbles: {
    position: "absolute",
    opacity: 0.6,
    width: 1000,
    zIndex: -1,
  },
  gameContainer: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  fullScreen: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  gameOverText: {
    color: "white",
    fontSize: 48,
  },
  congratulationsText: {
    color: "white",
    fontSize: 22,
    textAlign: "center",
    width: 300,
    flexWrap: "wrap",
  },
  nextLevelButton: {
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#fff",
    backgroundColor: "#22a1e6",
    color: "#eee",
    height: 35,
    width: 200,
    borderRadius: 35,
  },
  nextLevelButtonText: {
    alignItems: "center",
    justifyContent: "center",
    color: "#000",
    fontSize: 16,
  },
  mainMenuButton: {
    marginTop: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#fff",
    backgroundColor: "#22a1e6",
    color: "#eee",
    height: 35,
    width: 200,
    borderRadius: 35,
  },
  mainMenuButtonText: {
    alignItems: "center",
    justifyContent: "center",
    color: "#000",
    fontSize: 16,
  },
  statsContainer: {
    marginTop: Values.maxH - 100,
    paddingHorizontal: 20,
    width: Values.maxW,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statBoxes: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  statsCategory: {
    fontSize: 14,
    color: "#aaa",
  },
  statsValue: {
    fontSize: 24,
    fontWeight: "600",
    color: "#e4b23e",
  },
  keyContainer: {
    width: 50,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  key: {
    width: 40,
    height: 20,
  },
});

export default styles;
