import { StyleSheet } from "react-native";
import { ScaledSheet } from "react-native-size-matters";
// import { vw, vh, Dimensions } from "react-native-viewport-units";

import Values from "../helpers/Values";

// ORIGINAL ADJUSTMENTS
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#22a1e6",
    justifyContent: "center",
  },
  levelContainer: {
    width: Values.maxW,
    height: 450,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderColor: "#ddd",
    borderWidth: 0.5,
  },
  levelBackground: {
    position: "absolute",
    width: Values.maxW,
    height: 450,
    opacity: 0.3,
    borderColor: "#ddd",
    borderWidth: 0.5,
  },
  levelNameView: {
    position: "absolute",
    opacity: 0.97,
    paddingBottom: 287,
    flexDirection: "row",
    zIndex: 1,
  },
  levelCountText: {
    color: "#e4b23e",
    width: 65,
    fontSize: 11,
    paddingVertical: 10,
    textAlign: "center",
    paddingTop: 12,
    backgroundColor: "#111",
  },
  levelNameText: {
    width: 162,
    color: "#e0923e",
    fontWeight: "700",
    paddingLeft: 7,
    paddingTop: 5,
    fontSize: 20,
    backgroundColor: "#222",
  },
  imageWrapper: {
    width: Values.maxW,
    height: 450,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
    overflow: "hidden",
  },
  levelImage: {
    width: Values.maxW - 140,
    height: 370,
    marginTop: 0,
    opacity: 0.9,
    borderColor: "#fff",
    borderWidth: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  characterInfoContainer: {
    height: 220,
    marginTop: 15,
    justifyContent: "center",
  },
  characterCard: {
    width: Values.maxW,
    height: 220,
    marginVertical: 10,
    paddingTop: 12,
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "#eee",
    borderTopWidth: 2,
  },
  levelDetails: {
    flexDirection: "row",
    paddingHorizontal: 10,
  },
  characterPhotoContainer: {
    position: "absolute",
    width: 100,
    height: 100,
    backgroundColor: "rgba(237, 255, 242, 0.150)",
    marginLeft: 55,
    marginTop: 40,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 0.5,
    borderRadius: 100,
    borderColor: "#eee",
  },
  characterPhoto: {
    width: 70,
    height: 70,
  },
  characterName: {
    marginTop: -2,
    fontSize: 10,
    fontWeight: "500",
    width: 80,
    textAlign: "center",
    flexWrap: "wrap",
    color: "#eee",
  },
  statsCategory: {
    marginLeft: 180,
    fontSize: 12,
    letterSpacing: 0.55,
    color: "#ddd",
  },
  statsText: {
    fontWeight: "600",
    fontSize: 16,
  },
  statsHeading: {
    width: Values.maxW - 20,
    color: "#111",
    fontSize: 12,
    fontWeight: "400",
    textAlign: "center",
    letterSpacing: 2,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  userStats: {
    width: Values.maxW - 20,
    height: 200,
    opacity: 0.85,
    flexDirection: "column",
    justifyContent: "space-around",
    borderWidth: 2,
    borderRadius: 15,
    borderColor: "#222",
    marginHorizontal: 5,
    overflow: "hidden",
    backgroundColor: "#0e2f5e",
  },
  levelRequirementsContainer: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    width: Values.maxW,
    height: 500,
    zIndex: 10,
    paddingBottom: 177,
  },
  levelRequirements: {
    height: 75,
    width: Values.maxW - 148,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  objectives: {
    width: Values.maxW - 100,
    color: "#222",
    fontSize: 10,
    fontWeight: "500",
    letterSpacing: 7,
    textAlign: "center",
    marginHorizontal: 10,
    backgroundColor: "#fff",
  },
  objectiveItems: {
    width: Values.maxW - 148,
    color: "#e0923e",
    fontSize: 12,
    fontWeight: "300",
    letterSpacing: 0.8,
    textAlign: "center",
    paddingVertical: 3,
  },
  startButton: {
    position: "relative",
    width: 130,
    height: 40,
    borderWidth: 2.3,
    borderColor: "#222",
    borderRadius: 35,
    marginTop: -35,
    marginLeft: 23,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e4b23e",
  },
  start: {
    color: "#222",
    letterSpacing: 5,
    fontWeight: "600",
    fontSize: 15,
  },
});

// SOME % ADJUSTMENTS
// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//     backgroundColor: "#22a1e6",
//     justifyContent: "center",
//   },
//   levelContainer: {
//     width: Values.maxW,
//     height: Values.maxH / 1.9,
//     alignItems: "center",
//     justifyContent: "center",
//     overflow: "hidden",
//     borderColor: "#ddd",
//     borderWidth: 0.5,
//   },
//   levelBackground: {
//     position: "absolute",
//     width: Values.maxW,
//     height: Values.maxH / 1.9,
//     opacity: 0.3,
//     borderColor: "#ddd",
//     borderWidth: 0.5,
//   },
//   levelNameView: {
//     position: "absolute",
//     opacity: 0.97,
//     paddingBottom: Values.maxH / 3.72,
//     flexDirection: "row",
//     zIndex: 1,
//   },
//   levelCountText: {
//     color: "#e4b23e",
//     width: Values.maxW / 6,
//     fontSize: Values.maxW / 40,
//     paddingVertical: 10,
//     textAlign: "center",
//     paddingTop: 12,
//     backgroundColor: "#111",
//   },
//   levelNameText: {
//     width: Values.maxW / 2.8,
//     color: "#e0923e",
//     fontWeight: "700",
//     paddingLeft: 7,
//     paddingTop: 5,
//     fontSize: 24,
//     backgroundColor: "#222",
//   },
//   imageWrapper: {
//     width: Values.maxW,
//     height: Values.maxH / 1.9,
//     alignItems: "center",
//     justifyContent: "center",
//     backgroundColor: "#000",
//     overflow: "hidden",
//   },
//   levelImage: {
//     width: Values.maxW / 1.82,
//     height: Values.maxH / 2.3,
//     opacity: 0.9,
//     borderColor: "#fff",
//     borderWidth: 4,
//     borderRadius: 8,
//     overflow: "hidden",
//   },
//   characterInfoContainer: {
//     height: 220,
//     marginTop: 15,
//     justifyContent: "center",
//   },
//   characterCard: {
//     width: Values.maxW,
//     height: 220,
//     marginVertical: 10,
//     paddingTop: 12,
//     justifyContent: "center",
//     alignItems: "center",
//     borderTopColor: "#eee",
//     borderTopWidth: 2,
//   },
//   levelDetails: {
//     flexDirection: "row",
//     paddingHorizontal: 10,
//   },
//   characterPhotoContainer: {
//     position: "absolute",
//     width: 100,
//     height: 100,
//     backgroundColor: "rgba(237, 255, 242, 0.150)",
//     marginLeft: 55,
//     marginTop: 40,
//     justifyContent: "center",
//     alignItems: "center",
//     zIndex: 10,
//     borderWidth: 0.5,
//     borderRadius: 100,
//     borderColor: "#eee",
//   },
//   characterPhoto: {
//     width: 70,
//     height: 70,
//   },
//   characterName: {
//     marginTop: -2,
//     fontSize: 10,
//     fontWeight: "500",
//     width: 80,
//     textAlign: "center",
//     flexWrap: "wrap",
//     color: "#eee",
//   },
//   statsCategory: {
//     marginLeft: 180,
//     fontSize: 12,
//     letterSpacing: 0.55,
//     color: "#ddd",
//   },
//   statsText: {
//     fontWeight: "600",
//     fontSize: 16,
//   },
//   statsHeading: {
//     width: Values.maxW - 20,
//     color: "#111",
//     fontSize: 12,
//     fontWeight: "400",
//     textAlign: "center",
//     letterSpacing: 2,
//     justifyContent: "center",
//     backgroundColor: "#fff",
//   },
//   userStats: {
//     width: Values.maxW - 20,
//     height: 200,
//     opacity: 0.85,
//     flexDirection: "column",
//     justifyContent: "space-around",
//     borderWidth: 2,
//     borderRadius: 15,
//     borderColor: "#222",
//     marginHorizontal: 5,
//     overflow: "hidden",
//     backgroundColor: "#0e2f5e",
//   },
//   levelRequirementsContainer: {
//     position: "absolute",
//     justifyContent: "center",
//     alignItems: "center",
//     width: Values.maxW,
//     height: 500,
//     zIndex: 10,
//     paddingBottom: Values.maxH / 7,
//   },
//   levelRequirements: {
//     height: 75,
//     width: Values.maxW / 1.89,
//     justifyContent: "center",
//     alignItems: "center",
//     overflow: "hidden",
//     backgroundColor: "rgba(0, 0, 0, 0.75)",
//   },
//   objectives: {
//     width: Values.maxW / 1.89,
//     color: "#222",
//     fontSize: 10,
//     fontWeight: "500",
//     letterSpacing: 7,
//     textAlign: "center",
//     marginHorizontal: 10,
//     backgroundColor: "#fff",
//   },
//   objectiveItems: {
//     width: Values.maxW / 1.2,
//     color: "#e0923e",
//     fontSize: 12,
//     fontWeight: "300",
//     letterSpacing: 0.8,
//     textAlign: "center",
//     paddingVertical: 3,
//   },
//   startButton: {
//     position: "relative",
//     width: 130,
//     height: 40,
//     borderWidth: 2.3,
//     borderColor: "#222",
//     borderRadius: 35,
//     marginTop: -35,
//     marginLeft: 23,
//     justifyContent: "center",
//     alignItems: "center",
//     backgroundColor: "#e4b23e",
//   },
//   start: {
//     color: "#222",
//     letterSpacing: 5,
//     fontWeight: "600",
//     fontSize: 15,
//   },
// });

// SOME SIZE MATTERS ADJUSTMENTS
// const styles = ScaledSheet.create({
//   container: {
//     flex: 1,
//     backgroundColor: "#22a1e6",
//     justifyContent: "center",
//   },
//   levelContainer: {
//     width: `${Values.maxW}@s`,
//     height: "570@s",
//     alignItems: "center",
//     justifyContent: "center",
//     overflow: "hidden",
//     borderColor: "#ddd",
//     borderWidth: 0.5,
//   },
//   levelBackground: {
//     position: "absolute",
//     width: `${Values.maxW}@s`,
//     height: "570@ms",
//     opacity: 0.3,
//     borderColor: "#ddd",
//     borderWidth: 0.5,
//   },
//   levelNameView: {
//     position: "absolute",
//     opacity: 0.97,
//     paddingBottom: "410@s",
//     flexDirection: "row",
//     zIndex: 1,
//   },
//   levelCountText: {
//     color: "#e4b23e",
//     width: "80@s",
//     fontSize: "13@ms0.3",
//     paddingVertical: "10@vs",
//     textAlign: "center",
//     paddingTop: "12@vs",
//     backgroundColor: "#111",
//   },
//   levelNameText: {
//     width: "186@s",
//     color: "#e0923e",
//     fontWeight: "700",
//     paddingLeft: "7@s",
//     paddingTop: "5@vs",
//     fontSize: "24@ms0.3",
//     backgroundColor: "#222",
//   },
//   imageWrapper: {
//     width: Values.maxW,
//     height: "570@ms",
//     alignItems: "center",
//     justifyContent: "center",
//     backgroundColor: "#000",
//     overflow: "hidden",
//   },
//   levelImage: {
//     width: Values.maxW / 1.2,
//     height: "490@vs",
//     opacity: 0.9,
//     borderColor: "#fff",
//     borderWidth: "4@s",
//     borderRadius: 8,
//     overflow: "hidden",
//   },
//   characterInfoContainer: {
//     height: "220@vs",
//     marginTop: "15@vs",
//     justifyContent: "center",
//   },
//   characterCard: {
//     width: Values.maxW,
//     height: "220@vs",
//     marginVertical: "10@vs",
//     paddingTop: "12@vs",
//     justifyContent: "center",
//     alignItems: "center",
//     borderTopColor: "#eee",
//     borderTopWidth: "2@vs",
//   },
//   levelDetails: {
//     flexDirection: "row",
//     paddingHorizontal: "10@ms",
//   },
//   characterPhotoContainer: {
//     position: "absolute",
//     width: "100@s",
//     height: "100@vs",
//     backgroundColor: "rgba(237, 255, 242, 0.150)",
//     marginLeft: "55@ms",
//     marginTop: "40@ms",
//     justifyContent: "center",
//     alignItems: "center",
//     zIndex: 10,
//     borderWidth: 0.5,
//     borderRadius: 100,
//     borderColor: "#eee",
//   },
//   characterPhoto: {
//     width: 70,
//     height: 70,
//   },
//   characterName: {
//     marginTop: -2,
//     fontSize: 10,
//     fontWeight: "500",
//     width: 80,
//     textAlign: "center",
//     flexWrap: "wrap",
//     color: "#eee",
//   },
//   statsCategory: {
//     marginLeft: 180,
//     fontSize: 12,
//     letterSpacing: 0.55,
//     color: "#ddd",
//   },
//   statsText: {
//     fontWeight: "600",
//     fontSize: 16,
//   },
//   statsHeading: {
//     width: Values.maxW - 20,
//     color: "#111",
//     fontSize: 12,
//     fontWeight: "400",
//     textAlign: "center",
//     letterSpacing: 2,
//     justifyContent: "center",
//     backgroundColor: "#fff",
//   },
//   userStats: {
//     width: Values.maxW - 20,
//     height: 200,
//     opacity: 0.85,
//     flexDirection: "column",
//     justifyContent: "space-around",
//     borderWidth: 2,
//     borderRadius: 15,
//     borderColor: "#222",
//     marginHorizontal: "5@ms",
//     overflow: "hidden",
//     backgroundColor: "#0e2f5e",
//   },
//   levelRequirementsContainer: {
//     position: "absolute",
//     justifyContent: "center",
//     alignItems: "center",
//     width: Values.maxW,
//     height: "500@vs",
//     overflow: "hidden",
//     zIndex: 10,
//     paddingBottom: "297@ms",
//   },
//   levelRequirements: {
//     height: "75@vs",
//     width: Values.maxW,
//     justifyContent: "center",
//     alignItems: "center",
//     overflow: "hidden",
//     backgroundColor: "rgba(0, 0, 0, 0.75)",
//   },
//   objectives: {
//     width: Values.maxW,
//     color: "#222",
//     fontSize: "10@ms",
//     fontWeight: "500",
//     letterSpacing: "7@ms",
//     textAlign: "center",
//     marginHorizontal: "10@ms",
//     backgroundColor: "#fff",
//   },
//   objectiveItems: {
//     width: Values.maxW,
//     color: "#e0923e",
//     fontSize: "12@ms",
//     fontWeight: "300",
//     letterSpacing: 0.8,
//     textAlign: "center",
//     paddingVertical: 3,
//   },
//   startButton: {
//     position: "relative",
//     width: "130@s",
//     height: "40@vs",
//     borderWidth: 2.3,
//     borderColor: "#222",
//     borderRadius: "35@ms",
//     marginTop: "-35@ms",
//     marginLeft: "23@ms",
//     justifyContent: "center",
//     alignItems: "center",
//     backgroundColor: "#e4b23e",
//   },
//   start: {
//     color: "#222",
//     letterSpacing: 5,
//     fontWeight: "600",
//     fontSize: 15,
//   },
// });

export default styles;
