import { StyleSheet } from "react-native";
import Constants from "../helpers/Constants";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#22a1e6",
    justifyContent: "center",
    alignItems: "center",
  },
  levelsContainer: {
    width: Constants.maxWidth,
    height: 554,
    flexDirection: "row",
    backgroundColor: "#176d9c",
    justifyContent: "center",
    alignItems: "center",
    justifyContent: "center",
    borderTopColor: "#333",
    borderBottomColor: "#333",
    borderTopWidth: 1,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
  },
  midSection: {
    justifyContent: "center",
    alignItems: "center",
  },
  levelCard: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: Constants.maxWidth,
    height: 550,
    backgroundColor: "#22a1e6",

    overflow: "hidden",
  },
  levelNameView: {
    position: "absolute",
    paddingBottom: 500,
    flexDirection: "row",
  },
  levelNameText: {
    color: "#cff3ff",
    fontWeight: "700",
    fontSize: 30,
    textShadowColor: "#222",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  levelCountText: {
    color: "#cff3ff",
    fontSize: 16,
    paddingTop: 9,
    paddingRight: 8,
    textShadowColor: "#222",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  imageView: {
    width: Constants.maxWidth,
    height: 550,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderColor: "#ddd",
    borderWidth: 0.5,
    borderWidth: 0.5,
  },
  imageWrapper: {
    justifyContent: "center",
    alignItems: "center",
    width: Constants.maxWidth,
    backgroundColor: "#000",
    height: 550,
  },
  imageWrapperBackground: {
    position: "absolute",
    width: Constants.maxWidth,
    height: 550,
    opacity: 0.4,
    borderColor: "#ddd",
    borderWidth: 0.5,
    borderWidth: 0.5,
  },
  levelImage: {
    borderColor: "#fff",
    borderWidth: 4,
    marginTop: -70,
    width: 214,
    height: 380,
    opacity: 0.9,
  },
  arrows: {
    width: 13.6,
    height: 27.2,
    tintColor: "#f27f33",
    // opacity: 0.8,
  },
  characterInfoContainer: {
    width: Constants.maxWidth,
    backgroundColor: "#176d9c",
    height: 220,
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
    borderTopColor: "#333",
    borderBottomColor: "#333",
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
  },
  characterCard: {
    width: Constants.maxWidth,
    height: 220,
    marginVertical: 10,
    paddingVertical: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1f89c2",
    borderTopColor: "#eee",
    borderBottomColor: "#eee",
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
  },
  levelDetails: {
    flexDirection: "row",
    paddingHorizontal: 10,
    // justifyContent: "center",
    // alignItems: "center",
  },
  characterPhotoContainer: {
    position: "absolute",
    width: 100,
    height: 100,
    backgroundColor: "rgba(237, 255, 242, 0.150)",
    marginLeft: 40,
    marginTop: 40,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 0.5,
    borderRadius: 100,
    borderColor: "#eee",
  },
  characterPhoto: {
    width: 70,
    height: 70,
  },
  characterName: {
    marginTop: -8,
    fontSize: 11,
    fontWeight: "600",
    color: "#222",
    width: 80,
    textAlign: "center",
    flexWrap: "wrap",
    color: "#111",
  },
  stats: {
    marginLeft: 135,
    fontSize: 12,
    letterSpacing: 0.6,
    color: "#ddd",
  },
  statsHeading: {
    textAlign: "center",
    justifyContent: "center",
    fontWeight: "500",
    letterSpacing: 1.2,
    width: Constants.maxWidth - 20,
    color: "#222",
    fontSize: 13,
    backgroundColor: "#d5ebde",
  },
  userStats: {
    width: Constants.maxWidth - 20,
    backgroundColor: "#124e5e",
    opacity: 0.85,
    alignItems: "flex-start",
    justifyContent: "space-around",
    height: 200,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#222",
    marginHorizontal: 5,
  },
  levelRequirementsContainer: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    width: Constants.maxWidth,
    height: 500,
    zIndex: 10,
    paddingBottom: 300,
  },
  levelRequirements: {
    backgroundColor: "#124e5e",
    opacity: 0.85,
    justifyContent: "center",
    height: 100,
    width: Constants.maxWidth - 100,
    marginRight: 0,
    marginTop: 730,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#222",
    alignItems: "center",
    overflow: "hidden",
  },
  objectives: {
    textAlign: "center",
    color: "#222",
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 2.5,
    marginTop: 0,
    marginHorizontal: 10,
    width: Constants.maxWidth - 100,
    backgroundColor: "#d5ebde",
    textShadowColor: "#fff",
    textShadowOffset: { width: -0.2, height: 0.5 },
    textShadowRadius: 0.2,
  },
  objectiveItems: {
    marginTop: 8,
    fontSize: 16,
    letterSpacing: 0.8,
    fontWeight: "500",
    color: "#E4B23E",
  },
  startButtonContainer: {
    // justifyContent: "center",
    alignItems: "center",
  },
  startButton: {
    position: "absolute",
    borderWidth: 2,
    width: 150,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E4B23E",
    borderRadius: 35,
    marginTop: -55,
  },
  start: {
    color: "#222",
    letterSpacing: 2.5,
    fontWeight: "800",
    fontSize: 16,
  },
});

export default styles;
